stages:
  - pytest
  - quality
  - sonar

variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip

pytest:
  stage: pytest
  image: python:3.7 
  # several python versions in 1 image: quay.io/python-devs/ci-image
  before_script:
    - echo ===== update pip =====
    - python -m pip install -U pip
    - echo ===== install tox =====
    - pip install tox
    - echo ===== create folder for artifacts =====
    - mkdir test-reports
  script:
    - tox -e py
  artifacts:
    when: always
    paths:
      - ./**/test-reports/*.xml
    reports:
      junit: 
      - ./**/test-reports/*.xml 

black:
  stage: quality
  image: python:3.7 
  before_script:
    - echo ===== update pip =====
    - python -m pip install -U pip
    - echo ===== install tox =====
    - pip install tox
  script:
    - tox -e black

mypy:
  stage: quality
  image: python:3.7
  before_script:
    - echo ===== update pip =====
    - python -m pip install -U pip
    - echo ===== install tox =====
    - pip install tox
  script:
    - tox -e mypy

docs:
  stage: quality
  image: python:3.7
  before_script:
    - echo ===== update pip =====
    - python -m pip install -U pip
    - echo ===== install tox =====
    - pip install tox
  script:
    - tox -e docs    

pytest-master:
# run test using directly the pytest master branch  
  stage: pytest
  image: python:3.7
  before_script:
    - echo ===== update pip =====
    - python -m pip install -U pip
    - echo ===== install tox =====
    - pip install tox
    - echo ===== install poetry =====
    - apt-get update -qq
    - apt-get install curl -y -qq
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env
    - poetry config virtualenvs.create false

    - echo ==== retrieving pytest-master ====
    - poetry add git+https://github.com/pytest-dev/pytest.git#main

    - echo
    - echo ===== install requirements =====
    - poetry install --no-interaction --no-ansi
    - echo ===== create folder for artifacts =====    
    - mkdir test-reports
  script:
    - echo
    - echo ===== running tests with pytest-master =====
    - pytest --junitxml=test-reports/pytest.xml --cov=. --cov-report xml:test-reports/coverage.xml
  artifacts:
    when: always
    paths:
      - ./**/test-reports/*.xml
    reports:
      junit: 
      - ./**/test-reports/*.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"      

sonar:
  stage: sonar
  variables:
    SONAR_HOST_URL: $INS_SONAR_URL
    SONAR_LOGIN: $INS_SONAR_LOGIN
  image:
    name: sonarsource/sonar-scanner-cli
  script:
    - sonar-scanner -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.branch.name=$CI_BUILD_REF_NAME -Dsonar.python.coverage.reportPaths=test-reports/coverage.xml
  allow_failure: true
