[tool.poetry]
name = "pytest_nuts"
version = "0.1.0"
description = "Network Unit Testing System Component of NetTowel"
authors = ["Matthias Gabriel <matthias.gabriel@ins.hsr.ch>",
"Méline Sieber <meline.sieber@ins.hsr.ch",
"Urs Baumann <urs.baumann@ins.hsr.ch"]
classifiers=["Framework :: Pytest", "Development Status :: 3 - Alpha"]

[tool.poetry.dependencies]
python = "^3.6"
pytest = "^6.1.1"
PyYAML = "^5.3.1"
nornir = "^3.0.0"
nornir-napalm = "^0.1.1"
nornir-netmiko = "^0.1.1"
nornir-utils = "^0.1.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest-cov = "^2.10.1"

[tool.poetry.plugins."pytest11"]
"pytest_nuts"="pytest_nuts.plugin"

[tool.black]
line-length = 120

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:Using or importing the ABCs from 'collections':DeprecationWarning:napalm\\.base\\.helpers",
    "ignore:Using or importing the ABCs from 'collections':DeprecationWarning:jnpr\\.junos\\.factcache",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
