name: Run tests with tox
on: [push]
jobs:
  self-tests:
    name: pytest tests with tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
        testenv: py            
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - name: install tox
        run: pip install tox
      - name: run tox
        run: "tox -e ${{ matrix.testenv}}"
  quality:
    name: quality tests with tox
    runs-on: ubuntu-latest
    strategy:
      python: 3.7
      testenv: [mypy, flake8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - name: install tox
        run: pip install tox
      - name: run tox
        run: "tox -e ${{ matrix.testenv}}"