name: Run tests against pytest-master
on:
  schedule:
    - cron:  '* 22 * * 0'
jobs:
  self-tests:
    name: test against pytest-main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install tox
        run: pip install tox
      - name: run tox against pytest-main
        run: tox -e pytest-main